name: seamind-frontend
on:
  push:
    branches:
      - main
  pull_request_target:

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node: [14, 16, 18]
  #   name: Node ${{ matrix.node }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node }}
  #     - run: npm ci
  #     - run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        #  your build commands
        # - run: |
        #    ng build --prod
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token:
            ${{ secrets.VERCEL_TOKEN }} # Requireds
            # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}} #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./
          ALIAS_DOMAINS: |
            seamind.vercel.app
            {BRANCH}.seamind.vercel.app
          PR_PREVIEW_DOMAIN: '{REPO}-{PR}.now.sh'
